SEMANTICS_COURSEWORK_OWL_FILE = "Metro.owl"
SEMANTICS_COURSEWORK_XSLT_FILE = "owl_to_html.xslt"
SEMANTICS_COURSEWORK_PATH = r'/home/mashton/Documents/AI MSc/Semantics/Coursework/Python'
SEMANTICS_COURSEWORK_OWL_FQNAME = SEMANTICS_COURSEWORK_PATH + SEMANTICS_COURSEWORK_OWL_FILE
SEMANTICS_COURSEWORK_XSLT_FQNAME = SEMANTICS_COURSEWORK_PATH + SEMANTICS_COURSEWORK_XSLT_FILE
